/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/bind/invite" |
  "/pages/bind/join" |
  "/pages/bind/waiting" |
  "/pages/cook/categories" |
  "/pages/cook/dish-edit" |
  "/pages/cook/dishes" |
  "/pages/cook/order" |
  "/pages/cook/recipe" |
  "/pages/cook/record-edit" |
  "/pages/cook/records" |
  "/pages/cook/reject" |
  "/pages/cook/todo" |
  "/pages/eat/cancel" |
  "/pages/eat/confirm" |
  "/pages/eat/done" |
  "/pages/eat/menu" |
  "/pages/eat/order" |
  "/pages/eat/orders" |
  "/pages/eat/records" |
  "/pages/settings/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
